Update DomainToLegacyConverter
wmde/fundraising-memberships pull request #100
Opened 2022-05-20 13:14 UTC by Abban

2022-05-20 13:16 UTC, Abban commented on tests/Unit/LegacyConverters/DomainToLegacyConverterTest.php
>  	public function testWhenGivenNonModeratedNonCancelledApplicationWithUncompletedExternalPayment_setsNeutralStatus() {
Probably don't need this test, it may have been originally added as a safeguard or something.

2022-05-23 08:53 UTC, gbirke requested changes
You need to adapt the methods around the concept of a `confirmed` membership, which is about external payment providers, where the notification from the payment provider confirms the membership. Even if we don't have external payments at the moment  I think it's a good thing to be forwards-compatible. 

New memberships should be unconfirmed, until the `confirm` method is called. The confirmation status should be a boolean property. The converters should translate the confirmation status between the DB value and the boolean property.

The rest of the code looks good.

2022-05-23 08:53 UTC, gbirke commented on tests/Unit/LegacyConverters/DomainToLegacyConverterTest.php
> +			new LegacyPaymentData( 1, 1, 'UEB', [], LegacyPaymentStatus::EXTERNAL_BOOKED->value )
This combination of payment type and status does not make sense: `UEB` has `LegacyPaymentStatus::BANK_TRANSFER` and `BEZ` has `LegacyPaymentStatus::DIRECT_DEBIT`.

2022-05-23 16:41 UTC, gbirke requested changes
Sorry, I found 2 more things while re-reviewing

2022-05-25 08:37 UTC, gbirke approved these changes

2022-05-25 11:04 UTC, merged