Donation/Membership form postcode maximum field length validation
wmde/fundraising-memberships pull request #210
Opened 2024-08-27 12:18 UTC by Sperling-0

- Postcode validation allows 16 characters

Ticket: https://phabricator.wikimedia.org/T370617

2024-09-02 11:01 UTC, moiikana approved these changes

2024-09-03 13:11 UTC, gbirke requested changes

2024-09-03 13:11 UTC, gbirke commented on src/DataAccess/Migrations/Version20240826150940.php
> +		return '';
Please add a description

2024-09-03 13:11 UTC, gbirke commented on src/DataAccess/Migrations/Version20240826150940.php
> + * Auto-generated Migration: Please modify to your needs!
Please remove this comment

2024-09-03 13:49 UTC, gbirke requested changes

2024-09-03 13:49 UTC, gbirke commented on src/DataAccess/Migrations/Version20240826150940.php
> +		$schema->getTable( 'request' )->getColumn( 'postcode' )->setLength( 16 );
Sorry, the Migrations use the `real` column names from the database, not the ones from PHP
```suggestion
		$schema->getTable( 'request' )->getColumn( 'plz' )->setLength( 16 );
```

2024-09-03 13:49 UTC, gbirke commented on src/DataAccess/Migrations/Version20240826150940.php
> +		$schema->getTable( 'request' )->getColumn( 'postcode' )->setLength( 8 );
```suggestion
		$schema->getTable( 'request' )->getColumn( 'plz' )->setLength( 8 );
```

2024-09-03 14:37 UTC, gbirke approved these changes
User-tested, works now!

2024-09-03 17:48 UTC, gbirke commented
You can create release v16.2.0 after merging

2024-09-04 09:34 UTC, merged